import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import BubbleBackground from "@/components/BubbleBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GesturBee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gradient-to-b from-[#104846] to-[#00BFAF] text-[#373e50] relative overflow-hidden">
          <BubbleBackground></BubbleBackground>
          <div className="container mx-auto px-4 py-8 relative z-10">
            <Header></Header>

            {children}

            <footer className="mt-24 text-center text-white/70">
              <p>© 2025 GesturBee. All rights reserved.</p>
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
